name: VelocityDiscordLogger-Backend
version: 1.0.0
main: me.minseok.velocitydiscordloggerbackend.VelocityDiscordLoggerBackend
api-version: 1.21
authors: [minseok]
description: Backend plugin for VelocityDiscordLogger
commands:
  server:
    description: Connect to another server
    usage: /server <serverName>
    permission: velocitydiscordlogger.server
    permission-message: You do not have permission to use this command.
